DROP SEQUENCE STUDENT_SEQ;
CREATE SEQUENCE STUDENT_SEQ NOCACHE;

DROP TABLE STUDENT;
CREATE TABLE STUDENT (
    STU_NO NUMBER    NOT NULL,
    NAME   VARCHAR2(20 BYTE),
    KOR    NUMBER(3) CHECK(KOR BETWEEN 0 AND 100),
    ENG    NUMBER(3) CHECK(ENG BETWEEN 0 AND 100),
    MATH   NUMBER(3) CHECK(MATH BETWEEN 0 AND 100),
    AVE    NUMBER(5,2),
    GRADE  CHAR(1 BYTE),
    CONSTRAINT PK_STUDENT PRIMARY KEY(STU_NO)
);

INSERT INTO STUDENT VALUES(STUDENT_SEQ.NEXTVAL, '맥도날드', 90, 80, 70, (90 + 80 + 70)/3 , 'B');
INSERT INTO STUDENT VALUES(STUDENT_SEQ.NEXTVAL, '버거킹', 95, 85, 75, (95 + 85 + 75)/3 , 'A');
INSERT INTO STUDENT VALUES(STUDENT_SEQ.NEXTVAL, '롯데리아', 70, 80, 85, (70 + 80 + 85)/3 , 'C');